spring:
  datasource:
    url: jdbc:mysql://localhost:3306/changhong_springcloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static
  activemq:
    broker-url: tcp://localhost:61616
  application:
      name: consumer-movie
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true