
spring:
  application:
    name: 'discovery-eureka'

server:
  port: 8762

eureka:
#  instance:
#    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
security:
  basic:
    enabled: true # 开启basic认证
  user:
    name: ly
    password: 123

