server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://peer2:8762/eureka/'
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: 'discovery-eureka-jq-cluster'
